"""empty message

Revision ID: 76d388dccdbb
Revises: a5524ab34cf5
Create Date: 2020-04-20 00:47:48.234698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d388dccdbb'
down_revision = 'a5524ab34cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_day_object_id', table_name='day')
    op.create_index(op.f('ix_day_object_id'), 'day', ['object_id'], unique=False)
    op.drop_index('ix_state_object_id', table_name='state')
    op.create_index(op.f('ix_state_object_id'), 'state', ['object_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_object_id'), table_name='state')
    op.create_index('ix_state_object_id', 'state', ['object_id'], unique=1)
    op.drop_index(op.f('ix_day_object_id'), table_name='day')
    op.create_index('ix_day_object_id', 'day', ['object_id'], unique=1)
    # ### end Alembic commands ###
