"""empty message

Revision ID: 7f5b3e124c90
Revises: 44d621474eec
Create Date: 2018-06-25 17:08:30.495756

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7f5b3e124c90'
down_revision = '44d621474eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('remark', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'remark')
    # ### end Alembic commands ###
