"""empty message

Revision ID: a5524ab34cf5
Revises: 5984321e685d
Create Date: 2020-04-19 23:32:03.026110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5524ab34cf5'
down_revision = '5984321e685d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_day_country_id'), 'day', ['country_id'], unique=False)
    op.create_index(op.f('ix_day_state_id'), 'day', ['state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_state_id'), table_name='day')
    op.drop_index(op.f('ix_day_country_id'), table_name='day')
    # ### end Alembic commands ###
