"""empty message

Revision ID: b9b840945f16
Revises: 76d388dccdbb
Create Date: 2020-04-20 01:08:18.019295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b840945f16'
down_revision = '76d388dccdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_day_object_id', table_name='day')
    op.create_index(op.f('ix_day_object_id'), 'day', ['object_id'], unique=True)
    op.drop_index('ix_state_object_id', table_name='state')
    op.create_index(op.f('ix_state_object_id'), 'state', ['object_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_object_id'), table_name='state')
    op.create_index('ix_state_object_id', 'state', ['object_id'], unique=False)
    op.drop_index(op.f('ix_day_object_id'), table_name='day')
    op.create_index('ix_day_object_id', 'day', ['object_id'], unique=False)
    # ### end Alembic commands ###
