"""empty message

Revision ID: c883a5f613aa
Revises: 6b5881fedb30
Create Date: 2021-04-06 13:02:29.245840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c883a5f613aa'
down_revision = '6b5881fedb30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('is_Eid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'is_Eid')
    # ### end Alembic commands ###
